package Pages.HomeScreenOptions;

public enum Event {
    BIRTHDAY, INDEPENDENCE_DAY, BIRTH, THANKS, GET_WELL_SOON, FAREWELL, HINA, WEDDING, BAR_MITZVA, BAT_MITZVA,
    QUARANTINE, BECAUSE_I_WANT_TO, NEW_HOUSE, ANNIVERSARY, GOOD_LUCK, GIFT_TO_EMPLOYEES;
}
